name: Update Homebrew Formula (DISABLED - Formula managed manually)

# DISABLED: This workflow conflicts with manual formula management
# To re-enable: uncomment the 'on:' section below and ensure:
# 1. Create sojay/homebrew-tap repository
# 2. Add GH_PAT secret with repo permissions  
# 3. Move formula from homebrew/aznuke.rb to the tap repo

on:
  workflow_dispatch: # Manual trigger only (effectively disabled)

# NOTE: This workflow requires a GH_PAT secret with 'repo' permissions
# to push to the homebrew tap repository. Set this in repository secrets.

jobs:
  homebrew:
    runs-on: ubuntu-latest
    if: false  # Disabled
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: aznuke
          formula-path: homebrew/aznuke.rb
          homebrew-tap: sojay/homebrew-tap
          download-url: ${{ github.event.release.tarball_url }}
          commit-message: |
            {{formulaName}} {{version}}
            
            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_PAT }} 